services:
  database:
    image: postgres:16
    container_name: wecook_database
    env_file: .env.database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: backend/
    container_name: wecook_backend
    hostname: wecook
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file: .env.backend
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build: frontend/
    container_name: wecook_frontend
    restart: unless-stopped
    ports:
      - 3000:3000
